# -*- coding: utf-8 -*-
"""library-tugas-ks2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYW8SCCc9cHXdiZU0GaSHlUExNjnMt22
"""

# Factorial
def factorial(n):
    fac = 1
    for i in range(1, n+1):
        fac *= i    
    return fac

# Kombinasi
def kombinasi(n, x):
    comb = factorial(n)/(factorial(x) * factorial(n - x))
    return comb

# Permutasi
def permutasi(n, x):
    perm = factorial(n)/factorial(n - x)
    return perm

# Permutasi Siklis
def siklis(n):
    return factorial(n-1)

# Binomial Expansion
def binom_exp(n, r, a, b):
    coef = kombinasi(n, r) * (a**r) * (b**(n-r))
    return coef