# -*- coding: utf-8 -*-
"""Fungsi Matematika.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X0qhQKQzwXiWd6RGQAxSJ5nf-r6SOVGJ
"""

def l_bola(r): 
  luas = 4 * (22/7) * r**2 
  print("Luas bola dengan jari-jari", r,  
        "adalah sebesar", round(luas,3), "satuan.") 

def lp_tabung(r, t): 
  luas_permukaan = 2 * (22/7) * r * (r + t) 
  print("Luas permukaan tabung dengan jari-jari", r, "dan tinggi", t, 
        "adalah sebesar", round(luas_permukaan,3), "satuan.") 

def v_kerucut(r,t): 
  volume = 1/3 * (22/7) * r**2 *t 
  print("Volume kerucut dengan jari-jari", r, "dan tinggi", t,
        "adalah sebesar", round(volume,3), "satuan.") 

def kelsegitiga(alas, tinggi): 
    sisimiring = (((0.5*alas)**2)+(tinggi**2))**(1/2)
    keliling = (2*sisimiring)+alas 
    print ("Keliling dari segitiga dengan alas", alas , "dan tinggi", 
           tinggi, "adalah : ", keliling, "satuan") 

def volprisma3(alas,tinggisegi3,tinggi): 
    volume = ((alas*tinggisegi3)/2)*tinggi 
    print ("Volume dari prisma segitiga dengan alas", alas,
           ", tinggi alas segitiga",tinggisegi3, ", dan tinggi prisma", 
           tinggi, "adalah", volume, "satuan pangkat tiga")

